name: MicroFreakEditor
options:
  bundleIdPrefix: com.microfreakeditor
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: "5.0"

targets:
  MicroFreakEditor:
    type: application
    platform: [iOS, macOS]
    sources:
      - MicroFreakEditorApp
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.microfreakeditor.MicroFreakEditor
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      INFOPLIST_KEY_CFBundleDisplayName: MicroFreak Editor
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.music"
      INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
      # iPad only (no iPhone in v1)
      TARGETED_DEVICE_FAMILY: "2"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.microfreakeditor.MicroFreakEditor
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: MicroFreak Editor
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.music"
        INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: NO
        TARGETED_DEVICE_FAMILY: "2"
      iOS:
        CODE_SIGN_ENTITLEMENTS: MicroFreakEditorApp/MicroFreakEditor-iOS.entitlements
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      macOS:
        CODE_SIGN_ENTITLEMENTS: MicroFreakEditorApp/MicroFreakEditor-macOS.entitlements
